name: 'Custom Azuze Keyvault Extractor'
description: 'Reads secrets into the environment. parameters/{branch}.cfg required'
inputs:
  azure-client-secret:
    description: 'Azure Client Secret'
    required: true
  config:
    description: 'Input config file placed in parameters folder'
    requried: true
runs:
  using: "composite"
  steps:
    - name: Add Azure secrets to environment
      shell: bash
      env:
        AZURE_CLIENT_SECRET: ${{ inputs.azure-client-secret }}
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
        cd ${{ github.action_path }}
        poetry install --no-root
        poetry run python ${{ github.action_path }}/extract_azure_keyvault.py --branch ${{ inputs.config }} --root ${GITHUB_WORKSPACE}/parameters